export type StatutResultat = 'PROVISOIRE' | 'CORRIGE_STOCK' | 'ESTIME' | 'VALIDE';
export interface ResultatMensuelBoutique { poissonnerieId:number; poissonnerieNom:string; mois:number; annee:number; nombreJoursSaisis:number; dateDerniereCloture?:string; totalAchats:number; totalEncaissements:number; depensesJournalieres:number; chargesMensuelles:number; resultatProvisoire:number; dateSituationInitiale?:string; stockInitial?:number; creancesInitiales?:number; dateSituationFinale?:string; stockFinal?:number; creancesFinales?:number; creancesClientsCalculees:number; ecartCreancesClients?:number; variationStock?:number; variationCreances?:number; resultatCorrigeStock?:number; resultatValide?:number; statut:StatutResultat; informationsManquantes:string[]; alertes:string[]; }
export interface ResultatMensuelGlobal { mois:number; annee:number; boutiques:ResultatMensuelBoutique[]; totalAchats:number; totalEncaissements:number; totalDepensesJournalieres:number; totalChargesBoutiques:number; chargesGenerales:number; resultatProvisoire:number; variationStock?:number; variationCreances?:number; resultatCorrigeStock?:number; resultatValide?:number; statut:StatutResultat; informationsManquantes:string[]; alertes:string[]; }
export interface ResultatAnnuel { annee:number; mois:ResultatMensuelGlobal[]; totalAchats:number; totalEncaissements:number; totalDepenses:number; totalCharges:number; resultatProvisoire:number; resultatCorrigeStock?:number; resultatValide?:number; statut:StatutResultat; }
export type CategorieCharge = 'LOYER'|'ELECTRICITE'|'TRANSPORT'|'TAXES'|'SALAIRE'|'RATION'|'MANUTENTION'|'DIRECTION'|'AUTRE';
export interface CreateChargeGestionRequest { poissonnerieId?:number|null; categorie:CategorieCharge; libelle:string; montant:number; recurrente:boolean; dateDebut:string; dateFin?:string|null; }
export interface ChargeGestion extends CreateChargeGestionRequest { id:number; poissonnerieNom?:string; active:boolean; supprimee?:boolean; }
export interface SaveReleveSituationRequest { poissonnerieId:number; dateReleve:string; valeurStock:number; totalCreancesClients?:number|null; modeEvaluation:'COMPTAGE_PHYSIQUE'|'ESTIMATION'; note?:string; }
export interface ReleveSituation extends SaveReleveSituationRequest { id:number; poissonnerieNom:string; saisiParNom:string; createdAt:string; updatedAt:string; }
